# Generated by Django 5.0.6 on 2024-06-07 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('math', 'Mathematics'), ('science', 'Science'), ('english', 'English'), ('social_studies', 'Social Studies'), ('hindi', 'Hindi'), ('computer_science', 'Computer Science'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('history', 'History'), ('geography', 'Geography'), ('economics', 'Economics'), ('civics', 'Civics'), ('physical_education', 'Physical Education'), ('arts', 'Arts'), ('music', 'Music'), ('foreign_language', 'Foreign Language')], db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('english', 'English'), ('mandarin', 'Mandarin'), ('spanish', 'Spanish'), ('hindi', 'Hindi'), ('french', 'French'), ('arabic', 'Arabic'), ('bengali', 'Bengali'), ('russian', 'Russian'), ('portuguese', 'Portuguese'), ('urdu', 'Urdu')], db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_tutor', models.TextField(db_index=True)),
                ('job_title', models.CharField(db_index=True, max_length=100)),
                ('job_location', models.CharField(choices=[('online', 'Online'), ('Face-to-face', 'Face-to-face'), ('Home', 'Home')], db_index=True, default='online', max_length=100)),
                ('job_about', models.TextField(db_index=True)),
                ('salary_range', models.CharField(db_index=True, max_length=100)),
                ('publish', models.BooleanField(blank=True, db_index=True, default=True, null=True)),
                ('job_created', models.DateField(auto_now_add=True, db_index=True, null=True)),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job_lang', models.ManyToManyField(db_index=True, related_name='jobs', to='core_jobs.language')),
                ('job_subjects', models.ManyToManyField(db_index=True, related_name='jobs', to='core_jobs.subject')),
            ],
        ),
    ]
