# Generated by Django 5.0.6 on 2024-06-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='about_tutor',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_about',
            field=models.TextField(),
        ),
    ]
