# Generated by Django 5.0.6 on 2024-06-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_jobs', '0002_alter_job_about_tutor_alter_job_job_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary_range',
        ),
    ]
