# Generated by Django 5.0.6 on 2024-06-07 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0002_alter_tutee_info_alter_tutor_experience'),
        ('core_jobs', '0003_remove_job_salary_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_accounts.tutor'),
        ),
    ]
