# Generated by Django 5.0.6 on 2024-06-08 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_jobs', '0008_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
