# Generated by Django 5.0.6 on 2024-06-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_jobs', '0009_delete_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('english', 'English'), ('mandarin', 'Mandarin'), ('spanish', 'Spanish'), ('hindi', 'Hindi'), ('french', 'French'), ('arabic', 'Arabic'), ('bengali', 'Bengali'), ('russian', 'Russian'), ('portuguese', 'Portuguese'), ('urdu', 'Urdu')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('math', 'Mathematics'), ('science', 'Science'), ('english', 'English'), ('social_studies', 'Social Studies'), ('hindi', 'Hindi'), ('computer_science', 'Computer Science'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('history', 'History'), ('geography', 'Geography'), ('economics', 'Economics'), ('civics', 'Civics'), ('physical_education', 'Physical Education'), ('arts', 'Arts'), ('music', 'Music'), ('foreign_language', 'Foreign Language')], db_index=True, max_length=100),
        ),
    ]
