# Generated by Django 5.0.6 on 2024-06-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0002_alter_tutee_info_alter_tutor_experience'),
        ('core_jobs', '0007_alter_job_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='Response_time',
            field=models.CharField(db_index=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='degree',
            field=models.FileField(db_index=True, default=None, null=True, upload_to='degrees'),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hourly_rate',
            field=models.CharField(db_index=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='t_to_numver_of_students',
            field=models.CharField(db_index=True, default=None, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Tutee',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
