# Generated by Django 5.0.6 on 2024-06-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0004_reviews_user_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hourly_rate',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
