# Generated by Django 5.0.6 on 2024-06-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0005_alter_user_hourly_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Response_time',
            new_name='response_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='t_to_numver_of_students',
            new_name='t_to_number_of_students',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
    ]
