# Generated by Django 5.0.6 on 2024-06-20 03:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0009_user_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stages',
            field=models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Biology'), ('Third Year', 'Third Year'), ('Fourth Year (Bachelors)', 'Fourth Year (Bachelors)'), ('Masters (In Progress)', 'Masters (In Progress)'), ('PhD (In Progress)', 'PhD (In Progress)'), ('Bachelors Graduate', 'Bachelors Graduate'), ('Masters Graduate', 'Masters Graduate'), ('PhD Graduate', 'PhD Graduate')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subjects',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Biology', 'Biology'), ('Medicine', 'Medicine')], default=None, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
