# Generated by Django 5.0.6 on 2024-06-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0010_user_stages_user_subjects_passwordresettoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='subjects',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='user',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stages',
        ),
        migrations.AddField(
            model_name='user',
            name='stage',
            field=models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year (Bachelors)', 'Fourth Year (Bachelors)'), ('Masters (In Progress)', 'Masters (In Progress)'), ('PhD (In Progress)', 'PhD (In Progress)'), ('Bachelors Graduate', 'Bachelors Graduate'), ('Masters Graduate', 'Masters Graduate'), ('PhD Graduate', 'PhD Graduate')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.CharField(choices=[('University of Manchester', 'University of Manchester'), ('University College London', 'University College London'), ('University of York', 'University of York')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='profile/images'),
        ),
    ]
