# Generated by Django 5.0.6 on 2024-06-22 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0012_alter_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='users_messaging_container',
            field=models.ManyToManyField(related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
