# Generated by Django 5.0.6 on 2024-06-24 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0013_user_users_messaging_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_frame', models.CharField(max_length=50)),
                ('monday_from_time', models.TimeField(blank=True, null=True)),
                ('monday_to_time', models.TimeField(blank=True, null=True)),
                ('tuesday_from_time', models.TimeField(blank=True, null=True)),
                ('tuesday_to_time', models.TimeField(blank=True, null=True)),
                ('wednesday_from_time', models.TimeField(blank=True, null=True)),
                ('wednesday_to_time', models.TimeField(blank=True, null=True)),
                ('thursday_from_time', models.TimeField(blank=True, null=True)),
                ('thursday_to_time', models.TimeField(blank=True, null=True)),
                ('friday_from_time', models.TimeField(blank=True, null=True)),
                ('friday_to_time', models.TimeField(blank=True, null=True)),
                ('saturday_from_time', models.TimeField(blank=True, null=True)),
                ('saturday_to_time', models.TimeField(blank=True, null=True)),
                ('sunday_from_time', models.TimeField(blank=True, null=True)),
                ('sunday_to_time', models.TimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
